# Generated by Django 3.2.3 on 2021-05-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20210518_2028'),
        ('rareapi', '0002_auto_20210518_2030'),
    ]

    operations = [
    ]
